### ISSUE TITLE
Find a good name for the app ??

### ISSUE THREAD

**Issue by JulienParis** [JulienParis/LibViz#5]
LibViz ? LibNet ? 
Zot2Net ? 
VizZot ? 
Ref2Net ? RefNet ?

**Comment by JulienParis** [comment]
The last features allowing to pin down nodes (on the 'break-links' branch) gave me some ideas around the concept of weaving (tisser, les métiers à tisser) :
LibWiv ? Bibmill ? Twillib ? 
**Bibloom** (I like this one) ? 
Refloom ? **Loomit** ?

**Comment by nderambure** [comment]
LibViz won !
Close this :)

**Comment by JulienParis** [comment]
ok ! done
